apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: anc-portal

resources:
  - configmap.yaml
  - api-deployment.yaml
  - api-service.yaml
  - api-hpa.yaml
  - api-pdb.yaml
  - api-ingress.yaml
  - worker-deployment.yaml
  - migrate-job.yaml
  - sync-cronjob.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize

images:
  - name: ghcr.io/onizukazaza/anc-portal-be-fake
    newTag: latest
  - name: ghcr.io/anc-portal/anc-portal-worker
    newTag: latest
