// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Authenticate user with username and password, then return access token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login user",
                "parameters": [
                    {
                        "description": "Login payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_modules_auth_adapters_http.loginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login success",
                        "schema": {
                            "$ref": "#/definitions/github_com_onizukazaza_anc-portal-be-fake_internal_shared_dto.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "[10001] auth-bind-failed — request body ไม่ถูกต้อง",
                        "schema": {
                            "$ref": "#/definitions/github_com_onizukazaza_anc-portal-be-fake_internal_shared_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "[10002] auth-invalid-creds — username/password ไม่ถูกต้อง",
                        "schema": {
                            "$ref": "#/definitions/github_com_onizukazaza_anc-portal-be-fake_internal_shared_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "[10003] auth-internal-error — เกิดข้อผิดพลาดภายใน auth service",
                        "schema": {
                            "$ref": "#/definitions/github_com_onizukazaza_anc-portal-be-fake_internal_shared_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cmi/{job_id}/request-policy-single-cmi": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "ดึงข้อมูลงาน พรบ. เดี่ยว (Compulsory Motor Insurance) ตาม job_id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CMI"
                ],
                "summary": "Get CMI policy by job ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID",
                        "name": "job_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "CMI policy data",
                        "schema": {
                            "$ref": "#/definitions/github_com_onizukazaza_anc-portal-be-fake_internal_shared_dto.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "[12001] cmi-job-id-required — ไม่ได้ส่ง job_id",
                        "schema": {
                            "$ref": "#/definitions/github_com_onizukazaza_anc-portal-be-fake_internal_shared_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "[12002] cmi-job-not-found — ไม่พบ job",
                        "schema": {
                            "$ref": "#/definitions/github_com_onizukazaza_anc-portal-be-fake_internal_shared_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "[12003] cmi-internal-error — เกิดข้อผิดพลาดภายใน CMI service",
                        "schema": {
                            "$ref": "#/definitions/github_com_onizukazaza_anc-portal-be-fake_internal_shared_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/external-db/health": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Test connectivity of all registered external databases",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ExternalDB"
                ],
                "summary": "Check all external databases",
                "responses": {
                    "200": {
                        "description": "All database statuses",
                        "schema": {
                            "$ref": "#/definitions/github_com_onizukazaza_anc-portal-be-fake_internal_shared_dto.ApiResponse"
                        }
                    }
                }
            }
        },
        "/external-db/health/{name}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Test connectivity of a specific external database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ExternalDB"
                ],
                "summary": "Check external database by name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Database name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Database status",
                        "schema": {
                            "$ref": "#/definitions/github_com_onizukazaza_anc-portal-be-fake_internal_shared_dto.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "[13001] extdb-name-required — ไม่ได้ส่ง database name",
                        "schema": {
                            "$ref": "#/definitions/github_com_onizukazaza_anc-portal-be-fake_internal_shared_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "[13002] extdb-not-found — ไม่พบ database ที่ระบุ",
                        "schema": {
                            "$ref": "#/definitions/github_com_onizukazaza_anc-portal-be-fake_internal_shared_dto.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "[13003] extdb-unhealthy — database ไม่สามารถเชื่อมต่อได้",
                        "schema": {
                            "$ref": "#/definitions/github_com_onizukazaza_anc-portal-be-fake_internal_shared_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/quotations": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve paginated quotations for a given customer from external ERP database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Quotation"
                ],
                "summary": "List quotations by customer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Customer ID",
                        "name": "customerId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "created_at",
                            "doc_no",
                            "total_amount",
                            "status"
                        ],
                        "type": "string",
                        "description": "Sort column",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "asc",
                            "desc"
                        ],
                        "type": "string",
                        "default": "desc",
                        "description": "Sort order",
                        "name": "order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Paginated quotations",
                        "schema": {
                            "$ref": "#/definitions/github_com_onizukazaza_anc-portal-be-fake_internal_shared_dto.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "[11004] qt-customer-id-required — ไม่ได้ส่ง customerId",
                        "schema": {
                            "$ref": "#/definitions/github_com_onizukazaza_anc-portal-be-fake_internal_shared_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "[11005] qt-list-internal-error — เกิดข้อผิดพลาดขณะดึงรายการ quotation",
                        "schema": {
                            "$ref": "#/definitions/github_com_onizukazaza_anc-portal-be-fake_internal_shared_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/quotations/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve a single quotation from external ERP database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Quotation"
                ],
                "summary": "Get quotation by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Quotation ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Quotation data",
                        "schema": {
                            "$ref": "#/definitions/github_com_onizukazaza_anc-portal-be-fake_internal_shared_dto.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "[11001] qt-id-required — ไม่ได้ส่ง quotation id",
                        "schema": {
                            "$ref": "#/definitions/github_com_onizukazaza_anc-portal-be-fake_internal_shared_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "[11002] qt-not-found — ไม่พบ quotation",
                        "schema": {
                            "$ref": "#/definitions/github_com_onizukazaza_anc-portal-be-fake_internal_shared_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "[11003] qt-internal-error — เกิดข้อผิดพลาดภายใน quotation service",
                        "schema": {
                            "$ref": "#/definitions/github_com_onizukazaza_anc-portal-be-fake_internal_shared_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/webhooks/github": {
            "post": {
                "description": "Receives a push event from GitHub webhook and sends notification to Discord",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Webhook"
                ],
                "summary": "Receive GitHub push webhook",
                "parameters": [
                    {
                        "type": "string",
                        "description": "GitHub HMAC signature",
                        "name": "X-Hub-Signature-256",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "GitHub event type",
                        "name": "X-GitHub-Event",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Event processed",
                        "schema": {
                            "$ref": "#/definitions/github_com_onizukazaza_anc-portal-be-fake_internal_shared_dto.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "Unsupported event",
                        "schema": {
                            "$ref": "#/definitions/github_com_onizukazaza_anc-portal-be-fake_internal_shared_dto.ApiResponse"
                        }
                    },
                    "401": {
                        "description": "[14001] wh-invalid-signature — GitHub signature ไม่ถูกต้อง",
                        "schema": {
                            "$ref": "#/definitions/github_com_onizukazaza_anc-portal-be-fake_internal_shared_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "[14002] wh-process-failed — ประมวลผล webhook ล้มเหลว",
                        "schema": {
                            "$ref": "#/definitions/github_com_onizukazaza_anc-portal-be-fake_internal_shared_dto.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_onizukazaza_anc-portal-be-fake_internal_shared_dto.ApiResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "คำอธิบาย (\"success\", \"created successfully\", \"not found\")",
                    "type": "string"
                },
                "result": {
                    "description": "ข้อมูลผลลัพธ์ — null ถ้า error"
                },
                "status": {
                    "description": "\"OK\" หรือ \"ERROR\"",
                    "type": "string"
                },
                "status_code": {
                    "description": "HTTP status code (200, 201, 400, 500, ...)",
                    "type": "integer"
                }
            }
        },
        "github_com_onizukazaza_anc-portal-be-fake_internal_shared_dto.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "Error description",
                    "type": "string",
                    "example": "quotation not found"
                },
                "result": {
                    "description": "Contains trace_id",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_onizukazaza_anc-portal-be-fake_internal_shared_dto.ErrorResult"
                        }
                    ]
                },
                "status": {
                    "description": "\"ERROR\"",
                    "type": "string",
                    "example": "ERROR"
                },
                "status_code": {
                    "description": "HTTP status code",
                    "type": "integer",
                    "example": 400
                }
            }
        },
        "github_com_onizukazaza_anc-portal-be-fake_internal_shared_dto.ErrorResult": {
            "type": "object",
            "properties": {
                "trace_id": {
                    "description": "Error trace identifier",
                    "type": "string",
                    "example": "qt-not-found"
                }
            }
        },
        "internal_modules_auth_adapters_http.loginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "example": "secret123"
                },
                "username": {
                    "type": "string",
                    "example": "admin"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Input: Bearer {access_token}",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.1.0",
	Host:             "localhost:3000",
	BasePath:         "/v1",
	Schemes:          []string{"http"},
	Title:            "ANC Portal API",
	Description:      "Backend API for ANC Insurance Portal\n\n## Error Response Format\nทุก error response จะมี `trace_id` ใน `result` เพื่อระบุจุดที่เกิด error\n```json\n{\"status\":\"ERROR\",\"status_code\":404,\"message\":\"quotation not found\",\"result\":{\"trace_id\":\"qt-not-found\"}}\n```\n\n## Error Code Catalog\n> Source of truth: `internal/shared/dto/error_codes.go`\n\n| Module | Trace ID | Code | HTTP | คำอธิบาย |\n|--------|----------|------|------|---------|\n| Auth | auth-bind-failed | 10001 | 400 | request body ไม่ถูกต้อง |\n| Auth | auth-invalid-creds | 10002 | 401 | username/password ไม่ถูกต้อง |\n| Auth | auth-internal-error | 10003 | 500 | เกิดข้อผิดพลาดภายใน auth service |\n| Auth | auth-token-missing | 10004 | 401 | ไม่มี Authorization header หรือ token ว่าง |\n| Auth | auth-token-invalid | 10005 | 401 | token ไม่ถูกต้องหรือหมดอายุ |\n| Quotation | qt-id-required | 11001 | 400 | ไม่ได้ส่ง quotation id |\n| Quotation | qt-not-found | 11002 | 404 | ไม่พบ quotation |\n| Quotation | qt-internal-error | 11003 | 500 | เกิดข้อผิดพลาดภายใน quotation service |\n| Quotation | qt-customer-id-required | 11004 | 400 | ไม่ได้ส่ง customerId |\n| Quotation | qt-list-internal-error | 11005 | 500 | เกิดข้อผิดพลาดขณะดึงรายการ quotation |\n| CMI | cmi-job-id-required | 12001 | 400 | ไม่ได้ส่ง job_id |\n| CMI | cmi-job-not-found | 12002 | 404 | ไม่พบ job |\n| CMI | cmi-internal-error | 12003 | 500 | เกิดข้อผิดพลาดภายใน CMI service |\n| ExternalDB | extdb-name-required | 13001 | 400 | ไม่ได้ส่ง database name |\n| ExternalDB | extdb-not-found | 13002 | 404 | ไม่พบ database ที่ระบุ |\n| ExternalDB | extdb-unhealthy | 13003 | 503 | database ไม่สามารถเชื่อมต่อได้ |\n| Webhook | wh-invalid-signature | 14001 | 401 | GitHub signature ไม่ถูกต้อง |\n| Webhook | wh-process-failed | 14002 | 500 | ประมวลผล webhook ล้มเหลว |",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
